### ISSUE TITLE
p5 is not defined – in Firefox

### ISSUE THREAD

**Issue by jvolker** [therewasaguy/p5js-webIDE#115]
After pressing run with the starting code in Firefox the console of the webIDE reports: `Error on line 2: ReferenceError: p5 is not defined`

**Comment by therewasaguy** [comment]
The latest update should have fixed this by removing [this line](https://github.com/therewasaguy/p5js-webIDE/commit/37176533f79242b1f759e553bb7fe7d5624b6d4c#diff-bdf2da6adcfb8d4a4d7a170c700937d3L129) which is no longer necessary.

Can you try refreshing your browser cache and let me know if this error still appears?

**Comment by jvolker** [comment]
Thanks! Seems to be working now.
