### ISSUE TITLE
color for commas in editor window are very hard to see

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#20]
<img width="356" alt="screen shot 2015-08-20 at 11 21 48 am" src="https://cloud.githubusercontent.com/assets/191758/9387257/b3bbb93a-472d-11e5-9b5d-031b77d7927e.png">

**Comment by therewasaguy** [comment]
did a temporary fix, soon we'll have some official style suggestions for the editor css

https://github.com/therewasaguy/p5js-webIDE/commit/38eb1e970d435846fc145135ca0f1552b4519787
