### ISSUE TITLE
position for non-fullscreen canvas is awkward

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#21]
The top-right corner feels awkward to me and it is often obscured by the menu bar.  Perhaps something like centered in the area to the right of the code editor would work better.

<img width="1456" alt="screen shot 2015-08-20 at 11 22 43 am" src="https://cloud.githubusercontent.com/assets/191758/9387312/ed6b5eba-472d-11e5-919e-c279b550ad9e.png">

**Comment by therewasaguy** [comment]
resolved by changing the default CSS for the sketch, though I'm not sure if it's the ideal solution, I want to give the user control over this type of thing https://github.com/therewasaguy/p5js-webIDE/commit/17c012edf863d87542f38071b71f88e6bad1e51c

**Comment by shiffman** [comment]
I understand and agree.  I'm looking at this closely with the beginner "I've never seen any programming including javascript, html, or css before in my life" user in mind.  For this user, I think fullscreen sketches and custom positioning of sketches are a distraction.
