### ISSUE TITLE
Feedback on background re: projectors

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#52]
For teachers with a smart board, having a white or light-colored background (or configurable background) is an important feature.

(submitted live from SEP PD!)

**Comment by bensk** [comment]
Thanks! - the teacher who suggested that from the back for the room.

**Comment by therewasaguy** [comment]
Trying two themes for now, one light one dark, based on Jerel Johnson's recommendations. You can demo them at http://p5ide.herokuapp.com/ - hit the settings button to change the theme.

Custom ACE editor themes can be added / created / modified here:
- https://github.com/therewasaguy/p5js-webIDE/tree/master/app/editor/custom-themes

The theme variable ([here](https://github.com/therewasaguy/p5js-webIDE/blob/master/app/main.js#L74)) can also be added as a variable class name on the vue.js templates (like [here](https://github.com/therewasaguy/p5js-webIDE/blob/master/public/templates/index.html#L20)), and associated with theme-specific css (like [here](https://github.com/therewasaguy/p5js-webIDE/blob/master/app/window/window.scss#L29)). I've just started incorporating this and plan to keep going with it soon.

In the long run, it'd be fun to let users configure their own themes for the editor if not the entire app.
