### ISSUE TITLE
Sketchbook View

### ISSUE THREAD

**Issue by therewasaguy** [therewasaguy/p5js-webIDE#56]
...for browsing, sorting, searching and filtering "Your Sketchbook" and lists of projects in general.

Recent Projects dropdown is nice, but we need a better way to access "Your Sketchbook," which would contain all of your projects, and sketchbooks in general, which would contain all public projects that belong to a user.

I plan to use the existing dialog template and make something that resembles a file directory. Users can sort by date created, date modified, title. Also hope to add search/filter.

I'm not sure if it's worth trying to implement virtual "Folders," though it would be nice. I think Tags (https://github.com/therewasaguy/p5js-webIDE/issues/55) could be a more powerful way to organize sketchbooks.

Looked into something like [jstree](https://www.jstree.com/), and [list.js](www.listjs.com), and [vue.js has a great example](http://vuejs.org/examples/grid-component.html)

**Comment by shiffman** [comment]
Is this active?  I'm not seeing anything in the sketchbook under my account, but I assume that's just because it's a placeholder at this time?  I'm also not seeing anything under "recent", should that be working?

**Comment by therewasaguy** [comment]
Hmm, it should be active and it's working for me. Have you refreshed the page since saving?

It takes some time to load recent projects, so when first you load the page they don't show up immediately. And after saving a new project, there is some delay I haven't been able to pin down before it shows up in your recent projects. It looks so far like you have two projects that should show up...

**Comment by shiffman** [comment]
Unfortunately can't get it to work.  Tried logging in again via incognito window and safari.   We can look at this in person.

**Comment by therewasaguy** [comment]
This should be working now
