### ISSUE TITLE
save / save as / sketch name

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#60]
It's not clear to me the relationship between "save as" and the sketch name.  It seems like they are not related, as when I "save as" a new ID is generated and the name is just something floating on the page for human eyes.  But my expectation is that the "name" of a sketch is fundamental to the saving / save as-ing.  Not sure if I'm making any sense!  Am I?

**Comment by shiffman** [comment]
Looking at this a bit more, "save" doesn't seem to do anything, only "save as"?

**Comment by therewasaguy** [comment]
good call that right now you can Save As without renaming but creating a new project ID. And that's confusing.

How about each time you Save As, it checks against all the other project names and either
a. won't let you save over an existing project without confirming that that's what you want to do. Or,
b. lets you know if there's a match with some text like "save over existing project <project name>" if the name you have typed matches an existing project name.

Save should work like this: if any of the open files have asterisks by their names those should go away and the text at the top center will appear saying "saving..." followed by "project saved successfully". But if you try to save without making any changes it should say "Project is already up to date."

**Comment by shiffman** [comment]
This all sounds good.

Oh I see!  My confusion with "save" is that I was trying to click on the main "save" header link, and not unfurl the menu and click on the "save" below.   Would it make sense to have that main "save" trigger the save action itself?  I'm not sure what is standard.

I think all this will be much simpler once we have ⌘S too so I'm not worried too much!

**Comment by therewasaguy** [comment]
right, it's confusing that "save" and "open" are not clickable but look just like the other menu items which are clickable. I think they should either look different, or trigger some default action when clicked.

**Comment by therewasaguy** [comment]
- [x] save does not appear after "save as (user)" --> doesnt recognize that user now owns the project
- [x] after renaming by clicking on project name, add a field "oldName" to currentProject and this way show that the name has changed. From there, user should be able to save with the new name, or save as to save a copy.
- [x] if "save as" and there is already a project with that name, send that project's ID to the saveAs callback and overwrite it.
- [x] if "save as" and any of the project files were changed, make new files for them in the database.

**Comment by therewasaguy** [comment]
saving in general should be much more reliable now!
- save does not appear after "save as (user)" (fork) --> doesnt recognize that user has forked and now owns the project
  https://github.com/therewasaguy/p5js-webIDE/commit/ed9fd6b4b6e5f663a191f75ee95a00b3f467a4b0
- ability to rename
  https://github.com/therewasaguy/p5js-webIDE/commit/420d0fffc25aa6470585a6d60764de6e58de49b5
- if save as and there is already a project with that name, that project's id is sent as "overwriteID"
  https://github.com/therewasaguy/p5js-webIDE/commit/e4b9a940207b8cc499684e5f1056047a0af5bbfb#diff-3d4ab1f2c3e2f18229fb8d951e976712R18
- if "save as" and any of the project files were changed, make new files for them in the database:
  https://github.com/therewasaguy/p5js-webIDE/commit/e27edb8f0680e3af6b0ee242be11113fe106b4ca
