### ISSUE TITLE
code editor scroll to bottom

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#61]
This is a very minor thing (and perhaps it's an ACE issue), but I can't scroll to the very last line of code without it being slightly cutoff:

<img width="818" alt="screen shot 2016-01-03 at 5 18 21 pm" src="https://cloud.githubusercontent.com/assets/191758/12081104/23941088-b23e-11e5-92b6-0c98230555f2.png">

**Comment by shiffman** [comment]
Possibly related, when I switch to "run in new window", my code editor expands beyond the bottom of my browser page and then I cannot get to the end of the code.

<img width="1544" alt="screen shot 2016-01-03 at 5 22 50 pm" src="https://cloud.githubusercontent.com/assets/191758/12081124/bf87abbc-b23e-11e5-9f88-8c567432ca67.png">

**Comment by therewasaguy** [comment]
fixed up the editor css here and here

https://github.com/therewasaguy/p5js-webIDE/commit/ed94b3ef3235829d7fb667ea10076327f86f66ad#diff-98ef30860a3dcd63cd5d8128e423603aL24

https://github.com/therewasaguy/p5js-webIDE/commit/ed94b3ef3235829d7fb667ea10076327f86f66ad#diff-8a526bac6cabc95b3c872b7d3d95bf9aL13
