### ISSUE TITLE
Minimize / maximize code

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#63]
I'm finding the button placement for minimizing and maximizing the editor to be awkward as it moves after the code is minimized/maximized.  I have this sense that I should be able to toggle quickly and wonder if keeping that button in the same place on the header would be more intuitive?

Minimize:
<img width="813" alt="screen shot 2016-01-03 at 5 30 37 pm" src="https://cloud.githubusercontent.com/assets/191758/12081176/bf1e595e-b23f-11e5-97af-a0c1643ac783.png">

Maximize:
<img width="767" alt="screen shot 2016-01-03 at 5 30 43 pm" src="https://cloud.githubusercontent.com/assets/191758/12081177/c2fa61ee-b23f-11e5-898c-05356f799b37.png">

**Comment by therewasaguy** [comment]
the button stays in the same place now, and the chevron is gone!
https://github.com/therewasaguy/p5js-webIDE/commit/69b3d98c22ba2bcce2e5fa34217805e168f34df2
