### ISSUE TITLE
first time use editor "no p5" error

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#66]
I'm filing several issues that came up in class this morning.

Several students couldn't get anything to run in the editor their first attempt.  Only after creating a "NEW" sketch did things work.  Some of them saw a "no p5" error.  I didn't get a chance to look in the console or try to reproduce this.

**Comment by therewasaguy** [comment]
pretty sure this is fixed now, but let me know if it comes up again
