### ISSUE TITLE
Font color for strings (light theme)

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#68]
The font color for strings is the same gray as code comments which can cause some confusion.

<img width="615" alt="screen shot 2016-01-05 at 11 42 16 am" src="https://cloud.githubusercontent.com/assets/191758/12121081/7061bb72-b3a1-11e5-8615-513ebf145f67.png">

**Comment by therewasaguy** [comment]
tweaked this theme
https://github.com/therewasaguy/p5js-webIDE/commit/f34054711aab63d559bcd926448843e4c52e6f2e
