### ISSUE TITLE
Open sketchbook window should be wider / expandable

### ISSUE THREAD

**Issue by shiffman** [therewasaguy/p5js-webIDE#75]
![screen shot 2016-01-05 at 1 24 06 pm](https://cloud.githubusercontent.com/assets/191758/12123559/a41a7f72-b3af-11e5-8d59-c0251ba09907.png)

**Comment by therewasaguy** [comment]
fixed https://github.com/therewasaguy/p5js-webIDE/commit/9194e7be1a43a312e9be6f633d67f0e99cf6cafe
