### ISSUE TITLE
Broken sketch continues reloading

### ISSUE THREAD

**Issue by lucasfutch** [therewasaguy/p5js-webIDE#87]
Creating an infinite loop breaks the editor, and when trying to get back to the sketch, the editor keeps reloading. Is there a way reset or edit a sketch to fix without running it?

**Comment by therewasaguy** [comment]
oh no! This is a good reason not to autoplay sketches (https://github.com/therewasaguy/p5js-webIDE/issues/76)

Thinking up a temporary workaround, one second...

**Comment by lucasfutch** [comment]
I was able to fix this by deleting cookies/cache which logged me out of the p5 web editor, which allowed me to log in again and open the sketch to fix it without it attempting to reload.

**Comment by therewasaguy** [comment]
Ok try this:
1. go to some other address on the server that won't attempt to load or run the sketch, like this: http://p5ide.herokuapp.com/output
2. Open the javascript console (option-command-j on mac chrome)
3. type this into the console to get your user settings, tell it not to run in the page, and then reset:

```
var userSettings = JSON.parse(localStorage.userSettings);
userSettings.runInFrame = false
localStorage.userSettings = JSON.stringify(userSettings);
```

**Comment by therewasaguy** [comment]
ah, just saw your follow up @lucasfutch - nice workaround!

Closing this issue, but will make sure sketches don't autoplay unless you ask them to as part of #76
